### ISSUE TITLE
Question regarding gas transmittance calculation using libRadtran

### ISSUE THREAD

**Issue by sgxl** [EdGrrr/pyLRT#12]
Hi, thanks for maintaining the great open source code. I encountered some issues while using it and I’m looking for help. 

## Questions
I want to use libradtran to perform gas absorption correction of a satellite, but my results are different from the paper. This question has been bothering me for several days, so I’m posting this issue for help. 

I used verbose mode to obtain the H2O optical depth, then used spectral convolution method to obtain the optical depth of the satellite band, and used Beer-Lambert’s law to obtain the transmission.

* Ideal results:(snapshot from a paper)
![image](https://github.com/EdGrrr/pyLRT/assets/10265098/541f8fb4-ed20-4415-84c3-c682227c0516)

* my results:
It should be a curve, but it's a straight line
![image](https://github.com/EdGrrr/pyLRT/assets/10265098/3b9debd7-95a1-4023-b46b-21e12b3965bb)

## my code
```
from pyspectral.rsr_reader import RelativeSpectralResponse
from pyLRT import RadTran, get_lrt_folder
import matplotlib.pyplot as plt
LIBRADTRAN_FOLDER = get_lrt_folder()

# use pyspectral to read the RSR of the satellite
band = 'ch2'
sat = 'GOES-19'
sensor = 'abi'
rsr_obj = RelativeSpectralResponse(platform_name=sat, instrument=sensor)

wave_list = rsr_obj.rsr[band]['det-1']['wavelength'] * 1000
response_list = rsr_obj.rsr[band]['det-1']['response']
wave_min, wave_max = np.nanmin(wave_list), np.nanmax(wave_list)

# "options" in pyLRT is equal to the lines of libradtran input file
slrt = RadTran(LIBRADTRAN_FOLDER)
slrt.options['rte_solver'] = 'disort'
slrt.options['source'] = 'solar'
# slrt.options['wavelength'] = '200 2600'
slrt.options['output_user'] = 'lambda eglo eup edn edir'
slrt.options['zout'] = 'TOA'
slrt.options['albedo'] = '0'  # ignore the signal of surface

# setup the wavelength to the
slrt.options['wavelength'] = f'{wave_min:.0f} {wave_max:.0f}'


# loop each water vapour content
h2o_list = np.linspace(0, 100, 10)  # unit: mm

trans_list = []  # Result: Transmittance
for h2o in h2o_list:
    slrt_t = copy.deepcopy(slrt)
    slrt_t.options['mol_modify'] = f'H2O {h2o} MM'
    sdata, sverb = slrt_t.run(verbose=True)

    band_response_inter = np.interp(sverb['gases']['wvl'], wave_list, response_list, left=0, right=0)

    # h2o optical depth, two dimensions: (wavelength, vertical_layer)
    #  I've roughly read the source code of pyLRT, it read the output matrix of libradtran
    tau_h2o = sverb['gases']['h2o']

    # convolution each wavelength to band
    numerator = np.nansum(band_response_inter * tau_h2o.sum(axis=-1))
    denominator = np.nansum(band_response_inter)
    tau_h2o_band = numerator / denominator

    # Calculate transmittance using beer-lambert's law
    t = np.exp(-tau_h2o_band)
    trans_list.append(t)

plt.plot(np.array(h2o_list) / 10, trans_list)
plt.xlabel('Water Vapor Column Content [cm]')
plt.ylabel('Transmittance')
plt.title(f'{sat} {sensor} {band} libradtran')

plt.xlim([0, 10])
plt.ylim([0.95, 1])
plt.minorticks_on()
plt.tight_layout()
plt.show()
```

**Comment by EdGrrr** [comment]
Thanks for the report and the sample code - this is not the support for LibRadTran, but just a python wrapper. If you think there is an issue with libradtran itself, the libradtran team will be more use.

You can set pyLRT to print the file used for LibRadTran/uvspec with 'print_input=True' as an argument to the 'run' method.

It is tricky to know what the issue here is without knowing what you are trying to reproduce (which paper is it from) and I am not familiar with the PySpectral setup. However, LibRadTran has an option 'filter_function_file', which might help with the filtering.

**Comment by sgxl** [comment]
Thank you for your reply, I will study libradtran again, if it is solved, I will write a feedback here
