### ISSUE TITLE
Feature Request: Support for Multiple Command Inputs with Variable Arguments

### ISSUE THREAD

**Issue by FRomandACRI** [EdGrrr/pyLRT#13]
I'm beginning with libRadTran and pyLRT, but if I understand correctly, it is possible in LibRadTran to provide the same command several times in the configuration file. For example to set the total column of different molecular species:

mol_modify NO2 1.2 DU
mol_modify CH4 2.0e22 CM_2

Given that pyLRT utilizes a dictionary for simulation setup, it seems that achieving this isn't currently feasible. Only the 'mol_modify CH4 2.0e22 CM_2' command would actually take effect. Am I mistaken? Is there a workaround for this issue?

Many thanks to the developper, by the way.

**Comment by EdGrrr** [comment]
Could you try setting the option where the option name includes the molecule? I think this should work (but don't have a setup to check at the moment)

For example:

rt.options['mol_modify NO2'] = '1.2 DU'
rt.options['mol_modify CH4'] = '2.0e22 CM_2'

**Comment by FRomandACRI** [comment]
Thank you for the quick reply, I tried this method and obtained the error:
![error_pyLRT](https://github.com/EdGrrr/pyLRT/assets/127860954/bc1a5da2-555b-4248-a000-06ea24b7d95f)

Here's the script to reproduce it:

from pyLRT import RadTran, get_lrt_folder
import copy

LIBRADTRAN_FOLDER = get_lrt_folder()

slrt = RadTran(LIBRADTRAN_FOLDER)
slrt.options['rte_solver'] = 'disort'
slrt.options['aerosol_default'] = ''
slrt.options['aerosol_haze'] = '1'
slrt.options['wavelength'] = '1000 2200'
slrt.options['mol_abs_param'] = 'reptran coarse'
slrt.options['output_user'] = 'lambda uu'
slrt.options['zout'] = 'TOA'
slrt.options['albedo'] = '0.3'
slrt.options['umu'] = '1.'
slrt.options['sza'] = '45'
slrt.options['phi0'] = '90'
slrt.options['phi'] = '0'

slrt_corrected = copy.deepcopy(slrt)

slrt_corrected.options['mol_modify NO2'] = '1.2 DU'
slrt_corrected.options['mol_modify CH4'] = '2.0e22 CM_2'

sdata, sverb = slrt.run(verbose=True, print_input=True)
sdata_cor, sverb_cor = slrt_corrected.run(verbose=True, print_input=True)

**Comment by EdGrrr** [comment]
Sorry for the slow response - it turns out this is due to parsing the verbose output. You should be able to run this immediately by running your above code without the `verbose=True` argument to `slrt.run()`

There should now be a fix in master for this - let me know if it doesn't work.
