### ISSUE TITLE
Issue running pyLRT?

### ISSUE THREAD

**Issue by AndrewILWilliams** [EdGrrr/pyLRT#2]
Hi there!

I'm just trying to use this package to run the libradtran code, and I keep getting this error when I run your example code.

```
>>> from pyLRT import RadTran, get_lrt_folder
>>> get_lrt_folder()
'/gws/nopw/j04/aopp/andreww/side_projects/python_lbl_codes/libRadtran-2.0.4'
>>> LIBRADTRAN_FOLDER = get_lrt_folder()
>>> slrt = RadTran(LIBRADTRAN_FOLDER)
>>> slrt.options['rte_solver'] = 'disort'
>>> slrt.options['source'] = 'solar'
>>> slrt.options['wavelength'] = '200 2600'
>>> output = slrt.run(verbose=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/users/andreww/miniconda3/envs/libradtran/lib/python3.7/site-packages/pyLRT-0.2-py3.7.egg/pyLRT/RadTran.py", line 67, in run
  File "/home/users/andreww/miniconda3/envs/libradtran/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/users/andreww/miniconda3/envs/libradtran/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/users/andreww/miniconda3/envs/libradtran/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'uvspec': 'uvspec'
```

I've never used libradtran before and so I wondered if perhaps this was a simple fix? I'm not sure what `uvspec` refers to?

Thanks!
Andrew

**Comment by EdGrrr** [comment]
Hi Andrew - uvspec is the main libradtran program. You will need to compile libradtran first, which will create uvspec.

Once you have compiled libradtran/uvspec, pyLRT should be able to use it. The libradtran documentation (http://www.libradtran.org/doku.php?id=documentation) is also a really excellent resource for extra options etc.

Hope that helps!

**Comment by AndrewILWilliams** [comment]
Hey Ed, thanks this is very helpful! I'll give it a shot now. 

A

**Comment by AndrewILWilliams** [comment]
Just fyi, I had to change the `subprocess.run()` command in `RadTran` slightly to get this to work. 

I used `subprocess.run([os.getcwd()+'/uvspec'], ...)` instead of `subprocess.run(['uvspec'], ...)` and now it works. Probably something to do with different versions of `subprocess`? Not sure.

**Comment by EdGrrr** [comment]
Thanks Andrew - I'll add that into the code now, sounds like a useful addition (and doesn't seem to break anything in an obvious way).

Which version of python/subprocess are you using (just incase there is something funny going on)?

**Comment by AndrewILWilliams** [comment]
Hi Ed! I'm using python 3.7.10, I think this is tied to a specific version of subprocess? `subprocess.__version__` doesn't work but I think `subprocess` is a built-in python package?

**Comment by lmartinp** [comment]
I had to add the following to use the links in bash 

`        process = subprocess.run([os.getcwd()+'/uvspec'], stdout=subprocess.PIPE,
                                 stderr=subprocess.PIPE,
                                 input=inputstr, encoding='ascii', shell=True, executable='/bin/bash')`
