### ISSUE TITLE
Hello, thank you very much for open sourcing your code, but aerosols do not seem to be compatible. Are you going to add aerosols? I'm sure that's what a lot of people crave

### ISSUE THREAD

**Issue by sjj199405** [EdGrrr/pyLRT#5]

**Comment by EdGrrr** [comment]
Hi @sjj199405 - thanks for your interest in this project. I have nothing against adding aerosols, but as I don't use the aerosol features, it is not immediately clear to me what this should look like.

I'm closing this as a duplicate of #1 - but if you have an idea how you would like to use aerosols with this library, please add your thoughts there.

Ed
