### ISSUE TITLE
Hello, may I ask how to use libRadtran to calculate TOA(the spectral radiance at the top of atmosphere )？

### ISSUE THREAD

**Issue by aerosolwzt** [EdGrrr/pyLRT#9]
### Hello, may I ask how to use libRadtran to calculate TOA(the spectral radiance at the top of atmosphere )？
This is my first contact with libRadtran, now I need to use it to simulate TOA, may I ask how to set the input file? Do you have any examples?Thank you！

**Comment by EdGrrr** [comment]
Some of the examples show how to do this [such as this example](https://github.com/EdGrrr/pyLRT/blob/master/examples/nk90_plot.py)

If you need anything more complex, the libradtran forum is probably the best place to ask. the [libradtran manual](http://www.libradtran.org/doku.php?id=documentation) is also excellent
